import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'usStates'
})
export class UsStatesPipe implements PipeTransform {

  transform(value: any, ...args: unknown[]): unknown {
    let res = value
      .replace("AGU", "Aguas Calientes")
      .replace("BCN", "Baja California")
      .replace("BCS", "Baja California")
      .replace("CAM", "Campeche")
      .replace("CHP", "Chiapas")
      .replace("CHH", "Chihuahua")
      .replace("CMX3", "Ciudad de México")
      .replace("COA", "Coahuila")
      .replace("COL", "Colima")
      .replace("DUR", "Durango")
      .replace("GUA", "Guanajuato")
      .replace("GRO", "Guerrero")
      .replace("HID", "Hidalgo")
      .replace("JAL", "Jalisco")
      .replace("MEX", "México")
      .replace("MIC", "Michoacán")
      .replace("MOR", "Morelos")
      .replace("NAY", "Nayarit")
      .replace("NLE", "Nuevo León")
      .replace("OAX", "Oaxaca")
      .replace("PUE", "Puebla")
      .replace("QUE", "Querétaro")
      .replace("ROO", "Quintana")
      .replace("SLP", "San Luis Potosí")
      .replace("SIN", "Sinaloa")
      .replace("SON", "Sonora")
      .replace("TAB", "Tabasco")
      .replace("TAM", "Tamaulipas")
      .replace("TLA", "Tlaxcala")
      .replace("VER", "Veracruz")
      .replace("YUC", "Yucatán")
      .replace("ZAC", "Zacatecas")
      .replace("AL", "Alabama")
      .replace("AK", "Alaska")
      .replace("AZ", "Arizona")
      .replace("AR", "Arkansas")
      .replace("CA", "California")
      .replace("CO", "Colorado")
      .replace("CT", "Connecticut")
      .replace("DE", "Delaware")
      .replace("DC", "Distrito de Columbia")
      .replace("FL", "Florida")
      .replace("GA", "Georgia")
      .replace("HI", "Hawái")
      .replace("ID", "Idaho")
      .replace("IL", "Illinois")
      .replace("IN", "Indiana")
      .replace("IA", "Iowa")
      .replace("KS", "Kansas")
      .replace("KY", "Kentucky")
      .replace("LA", "Luisiana")
      .replace("ME", "Maine")
      .replace("MD", "Maryland")
      .replace("MA", "Massachusetts")
      .replace("MI", "Míchigan")
      .replace("MN", "Minnesota")
      .replace("MS", "Misisipi")
      .replace("MO", "Misuri")
      .replace("MT", "Montana")
      .replace("NE", "Nebraska")
      .replace("NV", "Nevada")
      .replace("NH", "Nuevo Hampshire")
      .replace("NJ", "Nueva Jersey")
      .replace("NM", "Nuevo México")
      .replace("NY", "Estado de Nueva York")
      .replace("NC", "Carolina del Norte")
      .replace("ND", "Dakota del Norte")
      .replace("OH", "Ohio")
      .replace("OK", "Oklahoma")
      .replace("OR", "Oregón")
      .replace("PA", "Pensilvania")
      .replace("RI", "Rhode Island")
      .replace("SC", "Carolina del Sur")
      .replace("SD", "Dakota del Sur")
      .replace("TN", "Tennessee")
      .replace("TX", "Texas")
      .replace("UT", "Utah")
      .replace("VT", "Vermont")
      .replace("VA", "Virginia")
      .replace("WA", "Estado de Washington")
      .replace("WV", "Virginia Occidental")
      .replace("WI", "Wisconsin")
      .replace("WY", "Wyoming")
      .replace("BC", "British Columbia")
      .replace("AB", "Alberta")
      .replace("SK", "Saskatchewan")
      .replace("MB", "Manitoba")
      .replace("ON", "Ontario")
      .replace("QC", "Quebec")
      .replace("NS", "Nova Scotia")
      .replace("NB", "New Brunswick")
      .replace("PE", "Prince Edward Island")
      .replace("NL", "Newfoundland and Labrador")
      .replace("NT", "Northwest Territories")
      .replace("YT", "Yukon")
      .replace("NU", "Nunavut")
      ;
    return res;
  }
}
